version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/app/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=budgetapp.settings
    command: "/idle.sh"
  db:
    build:
      context: .
      dockerfile: ./.devcontainer/db/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - budgetapp_postgres_data:/var/lib/postgresql/data
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"

volumes:
  budgetapp_postgres_data:
    external: true
